import { useState } from 'react';
import { Badge, Button, Card, Checkbox, DatePicker, EmptyState, Input, Modal, Radio, Select, Skeleton, StatusPill, Table, Tabs } from '../components/ui';
import '../styles/global.css';
import { useDocumentMeta } from '../lib/seo';

const tokenColors = [['Mandarine 100', 'var(--apik-mandarine-100)'], ['Mandarine 300', 'var(--apik-mandarine-300)'], ['Mandarine 500', 'var(--apik-mandarine-500)'], ['Mandarine 700', 'var(--apik-mandarine-700)'], ['Jaune 500', 'var(--apik-jaune-500)'], ['Turquoise 500', 'var(--apik-turquoise-500)'], ['Turquoise 700', 'var(--apik-turquoise-700)'], ['Encre', 'var(--apik-encre)'], ['Crème', 'var(--apik-creme)'], ['Conforme', 'var(--apik-conforme)'], ['Hors-taux', 'var(--apik-hors-taux)']];

export function Styleguide() {
  useDocumentMeta('Design system · Apik', 'Référence des composants et tokens visuels Apik.');
  const [modalOpen, setModalOpen] = useState(false);
  const [tab, setTab] = useState('tokens');
  return <main className="styleguide"><header className="styleguide__hero"><p className="styleguide__kicker">APiK · DESIGN SYSTEM</p><h1>Le bon composant, au bon moment.</h1><p>La bibliothèque de base pour une plateforme chaleureuse, lisible et conforme.</p></header><div className="styleguide__content"><Tabs tabs={[{ id: 'tokens', label: 'Tokens' }, { id: 'components', label: 'Composants' }]} activeTab={tab} onChange={setTab} />{tab === 'tokens' ? <TokenSection /> : <ComponentSection modalOpen={modalOpen} setModalOpen={setModalOpen} />}</div></main>;
}

function TokenSection() { return <div className="styleguide__section"><h2>Couleurs de la charte</h2><div className="swatches">{tokenColors.map(([name, color]) => <div className="swatch" key={name}><span style={{ background: color }} /><strong>{name}</strong><code>{color}</code></div>)}</div><h2>Échelle et formes</h2><div className="token-grid"><Card><h3>Typographie</h3><p className="display-text">Fredoka · Titres</p><p>Inter · données et texte courant</p><p className="muted">Corps 1.6 · titres 1.1 · graisses 400/500/600/700</p></Card><Card><h3>Espacements</h3><p>Échelle 4px : 4 · 8 · 12 · 16 · 20 · 24 · 28 · 32 px</p><p className="muted">Breakpoint charte : 640 px</p></Card><Card><h3>Rayons et ombres</h3><div className="radius-demo"><span /><span /><span /></div><p className="muted">18 px · 28 px · pilule · ombre charte</p></Card></div></div>; }

function ComponentSection({ modalOpen, setModalOpen }: { modalOpen: boolean; setModalOpen: (value: boolean) => void }) { return <div className="styleguide__section"><h2>Boutons et champs</h2><Card><div className="ui-row"><Button>Publier le créneau</Button><Button variant="secondary">Voir les profils</Button><Button variant="ghost">Plus tard</Button><Button variant="danger">Supprimer</Button><Button loading>Patienter</Button></div><div className="token-grid"><Input label="Nom de la structure" placeholder="École des Peupliers" hint="Pré-remplie depuis l'annuaire." /><Select label="Bloc périscolaire" defaultValue="morning"><option value="morning">Matin</option><option value="lunch">Midi</option><option value="evening">Soir</option></Select><DatePicker label="Date du créneau" /><div className="ui-stack"><Checkbox label="J'ai vérifié l'honorabilité" defaultChecked /><Radio label="Avec PEDT" name="pedt" defaultChecked /><Radio label="Sans PEDT" name="pedt" /></div></div></Card><h2>États et données</h2><Card><div className="ui-row"><Badge tone="info">Honorabilité vérifiée</Badge><Badge tone="success">Équipe conforme</Badge><Badge tone="warning">En attente</Badge><Badge tone="danger">Hors-taux</Badge><StatusPill tone="success">● Mission pourvue</StatusPill></div><Table headers={['Mission', 'Créneau', 'État']} rows={[["Accueil du matin", 'Demain · 7h30', <StatusPill key="one" tone="danger">-1 animateur</StatusPill>], ['Pause méridienne', 'Jeudi · 12h', <StatusPill key="two" tone="success">Conforme</StatusPill>]]} /></Card><div className="token-grid"><Card><h2>Chargement</h2><Skeleton height="1.4rem" /><Skeleton width="72%" /><Skeleton width="48%" /></Card><Card><h2>Vide</h2><EmptyState title="Aucune mission pour le moment">Les créneaux à pourvoir apparaîtront ici.</EmptyState></Card></div><Button variant="secondary" onClick={() => setModalOpen(true)}>Ouvrir la modal</Button><Modal open={modalOpen} title="Confirmer la mission" onClose={() => setModalOpen(false)}><p>Cette action lance le parcours de confirmation.</p><div className="ui-row modal-actions"><Button onClick={() => setModalOpen(false)}>Confirmer</Button><Button variant="ghost" onClick={() => setModalOpen(false)}>Annuler</Button></div></Modal></div>; }
