import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { useQueryClient } from '@tanstack/react-query';
import { Badge, Button, Card, StatusPill } from '../../components/ui';
import { useToast } from '../../components/ui';
import type { Availability, AnimatorProfile } from '../../lib/schemas';
import { api } from '../../lib/api';
import { animatorKeys, useAnimatorAvailability, useAnimatorProfile, useAnimatorTension, useAnimatorTensionCommunes, useAcceptAnimatorProposal, usePassAnimatorProposal } from './useAnimatorData';
import { useAnimatorProposals } from './useAnimatorProposals';
import { useOptionalAuth } from '../auth/AuthProvider';
import { useDocumentMeta } from '../../lib/seo';
import './animator.css';

const days = ['Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi'];
const blocks: { id: Availability['block']; label: string; hours: number }[] = [{ id: 'MORNING', label: 'Matin', hours: 1 }, { id: 'LUNCH', label: 'Midi', hours: 2 }, { id: 'EVENING', label: 'Soir', hours: 1.5 }, { id: 'WEDNESDAY', label: 'Mercredi', hours: 4.5 }];
const blockLabels: Record<Availability['block'], string> = { MORNING: 'Matin', LUNCH: 'Midi', EVENING: 'Soir', WEDNESDAY: 'Mercredi' };
const formatDate = (value: string) => new Intl.DateTimeFormat('fr-FR', { weekday: 'long', day: 'numeric', month: 'long' }).format(new Date(`${value}T12:00:00`));

function AnimatorLayout({ title, eyebrow, children }: { title: string; eyebrow: string; children: React.ReactNode }) { const auth = useOptionalAuth(); useDocumentMeta(`${title} · Apik`, `${eyebrow}. ${title}.`); return <main id="main-content" className="animator-page"><div className="animator-shell"><header className="animator-header"><div><Link className="animator-brand" to="/animateur" aria-label="Apik, espace animateur"><img src="/logo-apik.svg" alt="Apik" width="56" height="56" /></Link><p className="animator-eyebrow">{eyebrow}</p><h1>{title}</h1></div><nav className="animator-nav"><Link to="/animateur">Profil</Link><Link to="/animateur/disponibilites">Disponibilités</Link><Link to="/animateur/propositions">Propositions</Link><Link to="/animateur/agenda">Agenda</Link><Link to="/animateur/tension">Tension</Link>{auth && <button className="animator-logout" type="button" onClick={() => void auth.logout()}>Se déconnecter</button>}</nav></header>{children}</div></main>; }

 export function AnimatorProfilePage() { const profileQuery = useAnimatorProfile(); const profile = profileQuery.data; const locks = [{ title: 'Honorabilité', status: profile?.honorabilityStatus === 'VERIFIED', date: profile?.honorabilityCheckedAt?.slice(0, 10) ?? 'À vérifier', basis: 'CASF art. R227-3' }, { title: 'Diplôme', status: profile?.qualificationLevel === 'QUALIFIED', date: '2026-08-20', basis: 'CASF art. R227-12' }, { title: 'Pièce d’identité', status: true, date: 'Expire le 2028-04-12', basis: 'Contrôle d’identité Apik' }]; const blocked = locks.some((lock) => !lock.status); return <AnimatorLayout title={profile ? `${profile.firstName} ${profile.lastName}` : 'Mon profil animateur'} eyebrow="Espace animateur">{profile && <><div className="profile-intro"><div><p>{profile.city} · rayon de {profile.travelRadiusKm} km</p><h2>Un profil clair, des créneaux compatibles.</h2></div><StatusPill tone={profile.isSearching ? 'success' : 'warning'}>{profile.isSearching ? 'En recherche' : 'En pause'}</StatusPill></div><AnimatorProfileEditor profile={profile} /><div className="skill-row"><Badge tone="success">{profile.qualificationLevel === 'QUALIFIED' ? 'Diplômé' : profile.qualificationLevel}</Badge><Badge tone="info">{profile.experienceYears} ans d’expérience</Badge><Badge tone="neutral">6 ans et plus</Badge><Badge tone="neutral">Moins de 6 ans</Badge></div><section className="lock-section"><p className="animator-kicker">Sécurité et conformité</p><h2>Trois verrous, pas des critères</h2><p className="muted">Ces contrôles filtrent l’accès au moteur. Aucun score ne peut compenser un verrou non validé.</p>{blocked && <div className="lock-banner" role="alert">Profil retiré du moteur de mise en relation tant qu’un verrou n’est pas validé.</div>}<div className="lock-grid">{locks.map((lock) => <Card className={lock.status ? 'lock-card lock-card--ok' : 'lock-card lock-card--blocked'} key={lock.title}><div className="lock-card__top"><h3>{lock.title}</h3><StatusPill tone={lock.status ? 'success' : 'danger'}>{lock.status ? 'Validé' : 'À vérifier'}</StatusPill></div><p>{lock.date}</p><small>Fondement : {lock.basis}</small></Card>)}</div></section></>}</AnimatorLayout>; }

function AnimatorProfileEditor({ profile }: { profile: AnimatorProfile }) { const queryClient = useQueryClient(); const [firstName, setFirstName] = useState(profile.firstName); const [lastName, setLastName] = useState(profile.lastName); const [city, setCity] = useState(profile.city); const [travelRadiusKm, setTravelRadiusKm] = useState(String(profile.travelRadiusKm)); const [saved, setSaved] = useState(false); const save = async (event: React.FormEvent) => { event.preventDefault(); await api.put('/animators/profile', { firstName, lastName, city, travelRadiusKm: Number(travelRadiusKm) }); await queryClient.invalidateQueries({ queryKey: animatorKeys.profile }); setSaved(true); }; return <form className="profile-editor" onSubmit={(event) => void save(event)}><div className="profile-editor__fields"><label>Prénom<input value={firstName} onChange={(event) => setFirstName(event.target.value)} /></label><label>Nom<input value={lastName} onChange={(event) => setLastName(event.target.value)} /></label><label>Ville<input value={city} onChange={(event) => setCity(event.target.value)} /></label><label>Rayon (km)<input type="number" min="1" max="100" value={travelRadiusKm} onChange={(event) => setTravelRadiusKm(event.target.value)} /></label></div><Button type="submit" variant="secondary">Enregistrer le profil</Button>{saved && <span className="profile-editor__saved" role="status">Profil enregistré</span>}</form>; }

export function AnimatorAvailabilityPage() { const availabilityQuery = useAnimatorAvailability(); const [selected, setSelected] = useState<Set<string>>(new Set()); const refs = useRef<Array<HTMLButtonElement | null>>([]); const target = 35; const total = [...selected].reduce((sum, key) => sum + (blocks.find((block) => block.id === key.split('-')[1])?.hours ?? 0), 0); useEffect(() => { if (availabilityQuery.data) setSelected(new Set(availabilityQuery.data.data.map((item) => `${item.weekday}-${item.block}`))); }, [availabilityQuery.data]); const toggle = (dayIndex: number, blockIndex: number) => { const key = `${dayIndex + 1}-${blocks[blockIndex].id}`; setSelected((current) => { const next = new Set(current); if (next.has(key)) next.delete(key); else next.add(key); return next; }); }; const keyDown = (event: React.KeyboardEvent, dayIndex: number, blockIndex: number) => { if (event.key === ' ' || event.key === 'Enter') { event.preventDefault(); toggle(dayIndex, blockIndex); return; } const nextDay = event.key === 'ArrowRight' ? dayIndex + 1 : event.key === 'ArrowLeft' ? dayIndex - 1 : dayIndex; const nextBlock = event.key === 'ArrowDown' ? blockIndex + 1 : event.key === 'ArrowUp' ? blockIndex - 1 : blockIndex; if (nextDay >= 0 && nextDay < days.length && nextBlock >= 0 && nextBlock < blocks.length) { event.preventDefault(); refs.current[nextDay * blocks.length + nextBlock]?.focus(); } }; return <AnimatorLayout title="Mes disponibilités" eyebrow="Construire mon temps de travail"><Card className="availability-card"><div className="section-heading"><div><h2>Une semaine type</h2><p className="muted">Sélectionne les blocs où tu peux intervenir.</p></div><div className="hours-counter"><strong>{total.toFixed(1)} h</strong><span>objectif {target} h</span></div></div><div className="availability-grid" role="grid" aria-label="Disponibilités hebdomadaires" aria-rowcount={days.length} aria-colcount={blocks.length}>{days.map((day, dayIndex) => <div className="availability-row" role="row" key={day}><div className="availability-day" role="rowheader">{day}</div>{blocks.map((block, blockIndex) => { const key = `${dayIndex + 1}-${block.id}`; const active = selected.has(key); return <button className={`availability-cell ${active ? 'availability-cell--active' : ''}`} type="button" role="gridcell" aria-selected={active} tabIndex={dayIndex === 0 && blockIndex === 0 ? 0 : -1} ref={(element) => { refs.current[dayIndex * blocks.length + blockIndex] = element; }} onClick={() => toggle(dayIndex, blockIndex)} onKeyDown={(event) => keyDown(event, dayIndex, blockIndex)} key={block.id}><strong>{block.label}</strong><span>{block.hours} h</span></button>; })}</div>)}</div><div className="availability-summary"><span>{selected.size} blocs sélectionnés</span><span>{Math.max(0, target - total).toFixed(1)} h à compléter pour l’objectif</span></div></Card></AnimatorLayout>; }

export function AnimatorProposalsPage() { const proposalsQuery = useAnimatorProposals(); const accept = useAcceptAnimatorProposal(); const pass = usePassAnimatorProposal(); const { addToast } = useToast(); const [accepted, setAccepted] = useState<Set<string>>(new Set()); const [passed, setPassed] = useState<Set<string>>(new Set()); const [hours, setHours] = useState(15); const proposals = proposalsQuery.data?.data ?? []; const decide = async (id: string, action: 'accept' | 'pass') => { if (action === 'accept') { const proposal = proposals.find((item) => item.id === id); if (!proposal) return; setAccepted((current) => new Set(current).add(id)); setHours(proposal.hoursAfterAcceptance); try { await accept.mutateAsync(id); addToast('Créneau accepté : ton compteur d’heures est à jour.', 'info'); } catch { setAccepted((current) => { const next = new Set(current); next.delete(id); return next; }); addToast('Le créneau n’a pas pu être accepté.', 'error'); } } else { setPassed((current) => new Set(current).add(id)); await pass.mutateAsync(id); } }; return <AnimatorLayout title="Mes propositions" eyebrow="Des créneaux qui s’emboîtent"><div className="proposal-summary"><div><p className="animator-kicker">Cumul de la semaine</p><strong>{hours.toFixed(1)} h</strong><span>/ 35 h cible</span></div><Link to="/animateur/agenda">Voir mon agenda</Link></div><div className="proposal-list">{proposals.filter((proposal) => !passed.has(proposal.id)).map((proposal) => <Card className="proposal-card" key={proposal.id}><div className="proposal-card__top"><div><p className="animator-kicker">Compatible · {proposal.urgency === 'CRITICAL' ? 'pour demain' : 'cette semaine'}</p><h2>{proposal.title}</h2><p>École Jacques Prévert · Villeurbanne</p></div><Badge tone="success">{proposal.hourlyRateCents / 100} € / h</Badge></div><div className="proposal-facts"><span><strong>{proposal.distanceFromPreviousKm} km</strong><small>depuis ton créneau précédent</small></span><span><strong>{proposal.travelMinutes} min</strong><small>temps de trajet estimé</small></span><span><strong>{proposal.paidDurationHours} h</strong><small>durée payée</small></span></div><div className="proposal-actions"><Button variant="ghost" onClick={() => void decide(proposal.id, 'pass')}>Passer</Button><Button variant="secondary" disabled={accepted.has(proposal.id)} onClick={() => void decide(proposal.id, 'accept')}>{accepted.has(proposal.id) ? 'Accepté' : 'Accepter'}</Button></div></Card>)}</div></AnimatorLayout>; }

export function AnimatorAgendaPage() { const sessions = [{ date: '2026-09-14', block: 'MORNING' as const, employer: 'Les Petits Explorateurs', place: 'Jacques Prévert', hours: 1 }, { date: '2026-09-15', block: 'LUNCH' as const, employer: 'Villeurbanne Animation', place: 'École Anatole France', hours: 2 }, { date: '2026-09-17', block: 'EVENING' as const, employer: 'Les Petits Explorateurs', place: 'Jacques Prévert', hours: 1.5 }]; return <AnimatorLayout title="Mon agenda" eyebrow="Semaine du 14 au 20 septembre"><Card><p className="muted">Lecture seule · tes créneaux confirmés chez plusieurs employeurs.</p><div className="agenda-list">{sessions.map((session) => <div className="agenda-row" key={`${session.date}-${session.block}`}><time>{formatDate(session.date)}</time><div><strong>{blockLabels[session.block]}</strong><span>{session.place} · {session.employer}</span></div><Badge tone="info">{session.hours} h</Badge></div>)}</div></Card></AnimatorLayout>; }

export function AnimatorTensionPage() { const totalQuery = useAnimatorTension(); const communesQuery = useAnimatorTensionCommunes(); const total = totalQuery.data?.data[0]; return <AnimatorLayout title="Où ça recrute ?" eyebrow="Indicateur France Travail · ROME G1203"><div className="tension-hero"><div><p className="animator-kicker">Le marché autour de toi</p><h2>La tension devient un coup de pouce concret.</h2><p>Apik utilise les offres France Travail pour ajuster tes opportunités, pas pour t’afficher des données brutes.</p></div><strong>{total?.offerCount ?? 0}<small> offres dans le Rhône</small></strong></div><div className="tension-grid"><Card><p className="animator-kicker">Indicateur DARES</p><h2>{total?.tensionIndex ?? 0}</h2><p>Indice de tension sur le ROME G1203 · source France Travail / DARES.</p></Card><Card><p className="animator-kicker">Effet produit</p><h2>Délai conseillé : 24 h</h2><p>Quand la tension est forte, la diffusion est recommandée plus tôt et ton rayon passe automatiquement de 15 à 25 km pour ne pas rater un créneau compatible.</p></Card></div><Card><div className="section-heading"><div><p className="animator-kicker">Offres par commune</p><h2>Les zones les plus actives</h2></div><Badge tone="info">ROME G1203</Badge></div><div className="tension-table">{communesQuery.data?.data.map((item) => <div className="tension-row" key={item.id}><strong>{item.geoLabel}</strong><span>{item.offerCount} offres</span><StatusPill tone={item.tensionIndex && item.tensionIndex > 3 ? 'danger' : 'success'}>Indice {item.tensionIndex}</StatusPill></div>)}</div></Card></AnimatorLayout>; }
