import { useQuery } from '@tanstack/react-query';
import { Link, useParams } from 'react-router-dom';
import { Badge, Card, EmptyState, StatusPill } from '../../components/ui';
import { LogoApik } from '../../components/icons';
import { api } from '../../lib/api';
import { MissionSchema } from '../../lib/schemas';
import { useDocumentMeta } from '../../lib/seo';
import './public.css';

const proposal = "Permettre à un organisateur d'accueil périscolaire de combler un poste vacant avant le lendemain matin sans sortir de son taux d'encadrement réglementaire, et à un animateur de reconstituer un temps plein en cumulant des créneaux chez plusieurs employeurs.";
function PublicLayout({ children }: { children: React.ReactNode }) { return <main id="main-content" className="public-page"><header className="public-header"><Link className="public-brand" to="/" aria-label="Apik, accueil"><img src="/logo-apik.svg" alt="Apik" width="64" height="64" /></Link><nav><Link to="/missions/animateur-periscolaire-jeudi-soir-jacques-prevert">Missions</Link><Link to="/connexion">Se connecter</Link></nav></header>{children}<footer><img src="/logo-apik.svg" alt="Apik" width="40" height="40" /><nav><Link to="/inscription">Créer un compte</Link><Link to="/confidentialite">Confidentialité</Link><Link to="/cgu">CGU</Link></nav></footer></main>; }

export function HomePage() { useDocumentMeta('Apik · L’animateur qui arrive à pic', 'Apik relie le calcul du taux d’encadrement au recrutement périscolaire urgent.'); return <PublicLayout><section className="public-hero"><h1 className="public-hero__logo"><LogoApik size={320} title="Apik" /></h1><p className="public-kicker public-tagline">L’animateur qui arrive à pic.</p><p className="public-value">{proposal}</p><div className="public-actions"><Link className="public-button public-button--primary" to="/inscription/structure">Je suis une structure</Link><Link className="public-button public-button--secondary" to="/inscription/animateur">Je suis animateur</Link></div></section><section className="public-band"><p className="public-kicker">Le moteur Apik</p><h2>Calculer avant de recruter.</h2><p>Le besoin naît quand le créneau passe sous son seuil réglementaire. Le matching part ensuite avec des verrous d’honorabilité, de disponibilité et de qualification.</p></section></PublicLayout>; }

export function PublicMissionPage() { const { slug = '' } = useParams(); const query = useQuery({ queryKey: ['public-mission', slug], queryFn: () => api.get(`/public/missions/${slug}`, MissionSchema) }); const mission = query.data; useDocumentMeta(mission ? `${mission.title} · Apik` : 'Mission périscolaire · Apik', mission?.description ?? 'Une mission périscolaire Apik.'); return <PublicLayout>{mission ? <article className="public-mission"><p className="public-kicker">Mission {mission.reference}</p><h1>{mission.title}</h1><p className="public-mission__lead">{mission.description}</p><div className="public-mission__grid"><Card><h2>Le besoin</h2><dl className="public-details"><div><dt>Lieu</dt><dd>École Jacques Prévert · Villeurbanne</dd></div><div><dt>Créneau</dt><dd>Jeudi soir · 17 septembre · 16h30 à 18h</dd></div><div><dt>Rémunération</dt><dd>{(mission.hourlyRateCents / 100).toFixed(2)} € brut / heure</dd></div><div><dt>Conformité</dt><dd><StatusPill tone="danger">1 animateur manque</StatusPill></dd></div></dl></Card><Card><h2>Profil recherché</h2><p>Une expérience auprès d’enfants de 6 à 10 ans et un BAFA, CPJEPS ou BPJEPS sont les bienvenus.</p><Badge tone="info">ROME {mission.romeCode}</Badge><Link className="public-button public-button--primary" to="/inscription/animateur">Proposer mon profil</Link></Card></div></article> : <EmptyState title={query.isLoading ? 'Chargement de la mission...' : 'Mission introuvable'} />}</PublicLayout>; }
