import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Badge, Button, Card, EmptyState, StatusPill } from '../../components/ui';
import { calculateQualificationQuota } from '../../domain/qualificationQuota';
import { calculateSupervisionRatio } from '../../domain/supervisionRatio';
import { demoMission } from '../../mocks/fixtures';
import type { Candidate, CareSession, EmployerProfile, Mission } from '../../lib/schemas';
import { useToast } from '../../components/ui';
import { useQueryClient } from '@tanstack/react-query';
import { queryKeys } from '../queryKeys';
import { useOptionalAuth } from '../auth/AuthProvider';
import { useDocumentMeta } from '../../lib/seo';
import { api } from '../../lib/api';
import { useAcceptCandidate, useEmployerContracts, useEmployerMatchRun, useEmployerMissions, useEmployerProfile, useEmployerSchool, useEmployerSessions, useRemoveAnimator } from './hooks';
import './employer.css';

const blocks: CareSession['block'][] = ['MORNING', 'LUNCH', 'EVENING', 'WEDNESDAY'];
const blockLabels: Record<CareSession['block'], string> = { MORNING: 'Matin', LUNCH: 'Midi', EVENING: 'Soir', WEDNESDAY: 'Mercredi' };
const statusLabels: Record<Mission['status'], string> = { DRAFT: 'Brouillon', OPEN: 'Ouverte', FILLED: 'Pourvue', COMPLETED: 'Terminée', CANCELLED: 'Annulée', EXPIRED: 'Expirée' };
const formatDate = (value: string) => new Intl.DateTimeFormat('fr-FR', { weekday: 'short', day: 'numeric', month: 'short' }).format(new Date(`${value}T12:00:00`));

function EmployerLayout({ title, eyebrow, children }: { title: string; eyebrow: string; children: React.ReactNode }) { const auth = useOptionalAuth(); useDocumentMeta(`${title} · Apik`, `${eyebrow}. ${title}.`); return <main id="main-content" className="employer-page"><div className="employer-shell"><header className="employer-header"><div><Link className="employer-brand" to="/employeur" aria-label="Apik, espace employeur"><img src="/logo-apik.svg" alt="Apik" width="56" height="56" /></Link><p className="employer-eyebrow">{eyebrow}</p><h1>{title}</h1></div><nav className="employer-nav"><Link to="/employeur">Dashboard</Link><Link to="/employeur/planning">Planning</Link><Link to="/employeur/missions/mission-thu-evening">Mission urgente</Link>{auth && <button className="employer-logout" type="button" onClick={() => void auth.logout()}>Se déconnecter</button>}</nav></header>{children}</div></main>; }

export function EmployerDashboardPage() {
  const sessionsQuery = useEmployerSessions(); const missionsQuery = useEmployerMissions(); const profileQuery = useEmployerProfile(); const [schoolFilter, setSchoolFilter] = useState('all'); const [weekFilter, setWeekFilter] = useState('2026-09-14'); const [statusFilter, setStatusFilter] = useState<'ALL' | Mission['status']>('ALL');
  const sessions = sessionsQuery.data?.data ?? []; const missions = missionsQuery.data?.data ?? []; const compliant = sessions.filter((session) => session.complianceStatus === 'COMPLIANT').length; const defective = sessions.length - compliant;
  const filteredMissions = missions.filter((mission) => statusFilter === 'ALL' || mission.status === statusFilter).filter((mission) => schoolFilter === 'all' || mission.siteId === schoolFilter).filter((mission) => mission.startDate >= weekFilter && mission.startDate <= '2026-09-20');
    return <EmployerLayout title="Garder l’équipe dans les clous" eyebrow="Espace employeur"><section className="employer-hero"><div><p className="employer-kicker">Jeudi 17 septembre · Jacques Prévert</p><h2>Un créneau sous le seuil ? Apik le voit avant toi.</h2><p>Le calcul réglementaire pilote directement la diffusion du besoin.</p></div><Link className="employer-primary-link" to="/employeur/planning">Ouvrir le planning</Link></section>{profileQuery.data && <EmployerProfileEditor profile={profileQuery.data} />}<div className="metric-grid"><Metric label="Créneaux conformes" value={compliant} tone="success" /><Metric label="Créneaux en défaut" value={defective} tone="danger" /><Metric label="Missions ouvertes" value={missions.filter((mission) => mission.status === 'OPEN').length} tone="warning" /><Metric label="Missions pourvues" value={missions.filter((mission) => mission.status === 'FILLED').length} tone="info" /></div><Card><div className="section-heading"><div><p className="employer-kicker">Suivi des besoins</p><h2>Missions de la semaine</h2></div><Link to="/employeur/planning">Voir le planning</Link></div><div className="filter-row"><label>École<select value={schoolFilter} onChange={(event) => setSchoolFilter(event.target.value)}><option value="all">Toutes les écoles</option><option value="school-jacques-prevert">Jacques Prévert</option></select></label><label>Semaine<input type="date" value={weekFilter} onChange={(event) => setWeekFilter(event.target.value)} /></label><label>Statut<select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value as typeof statusFilter)}><option value="ALL">Tous les statuts</option>{(['OPEN', 'FILLED', 'COMPLETED'] as const).map((status) => <option value={status} key={status}>{statusLabels[status]}</option>)}</select></label></div>{filteredMissions.length ? <div className="mission-list">{filteredMissions.map((mission) => <Link className="mission-row" to={`/employeur/missions/${mission.id}`} key={mission.id}><span><strong>{mission.title}</strong><small>{formatDate(mission.startDate)} · {blockLabels[mission.block]} · {mission.reference}</small></span><StatusPill tone={mission.status === 'OPEN' ? 'warning' : mission.status === 'FILLED' ? 'success' : 'info'}>{statusLabels[mission.status]}</StatusPill></Link>)}</div> : <EmptyState title="Aucune mission pour ces filtres">Le prochain besoin apparaîtra ici dès qu’un seuil sera franchi.</EmptyState>}</Card></EmployerLayout>;
}
function EmployerProfileEditor({ profile }: { profile: EmployerProfile }) { const queryClient = useQueryClient(); const [name, setName] = useState(profile.name); const [city, setCity] = useState(profile.city); const [contactEmail, setContactEmail] = useState(profile.contactEmail); const [saved, setSaved] = useState(false); const save = async (event: React.FormEvent) => { event.preventDefault(); await api.put('/employer/profile', { name, city, contactEmail }); await queryClient.invalidateQueries({ queryKey: ['employer', 'profile'] }); setSaved(true); }; return <form className="employer-profile-editor" onSubmit={(event) => void save(event)}><p className="employer-kicker">Organisation</p><div><label>Nom<input value={name} onChange={(event) => setName(event.target.value)} /></label><label>Ville<input value={city} onChange={(event) => setCity(event.target.value)} /></label><label>Email<input type="email" value={contactEmail} onChange={(event) => setContactEmail(event.target.value)} /></label></div><Button type="submit" variant="secondary">Enregistrer l’organisation</Button>{saved && <span className="profile-editor__saved" role="status">Organisation enregistrée</span>}</form>; }
function Metric({ label, value, tone }: { label: string; value: number; tone: 'success' | 'danger' | 'warning' | 'info' }) { return <Card className={`metric metric--${tone}`}><span>{label}</span><strong>{value}</strong></Card>; }

export function EmployerPlanningPage() {
  const sessionsQuery = useEmployerSessions(); const schoolQuery = useEmployerSchool('school-jacques-prevert'); const removeAnimator = useRemoveAnimator(); const queryClient = useQueryClient(); const { addToast } = useToast(); const navigate = useNavigate(); const [sessions, setSessions] = useState<CareSession[]>([]); const [selected, setSelected] = useState<CareSession | null>(null);
  useEffect(() => { if (sessionsQuery.data) setSessions(sessionsQuery.data.data); }, [sessionsQuery.data]);
  const dates = ['2026-09-14', '2026-09-15', '2026-09-16', '2026-09-17', '2026-09-18']; const hasPedt = schoolQuery.data?.hasPedt ?? true;
  const selectedResult = selected ? calculateSupervisionRatio({ childrenUnder6: selected.childrenUnder6, children6AndOver: selected.children6AndOver, hasPedt, durationHours: (selected.endMinutes - selected.startMinutes) / 60, presentStaff: selected.assignedStaffTotal }) : null;
  const quota = selected ? calculateQualificationQuota({ qualified: selected.qualifiedCount, trainee: selected.traineeCount, unqualified: selected.unqualifiedCount }) : null;
  const remove = async () => { if (!selected) return; await removeAnimator.mutateAsync(selected.id); const nextAssigned = Math.max(0, selected.assignedStaffTotal - 1); const next = { ...selected, assignedStaffTotal: nextAssigned, complianceStatus: nextAssigned >= selected.requiredStaffTotal ? 'COMPLIANT' as const : 'STAFF_SHORTAGE' as const }; setSessions((current) => current.map((session) => session.id === selected.id ? next : session)); setSelected(next); queryClient.setQueryData<{ data: CareSession[]; total: number }>(queryKeys.sessions, (current) => current ? { ...current, data: current.data.map((session) => session.id === next.id ? next : session) } : current); if (next.complianceStatus === 'STAFF_SHORTAGE') { const mission = { ...demoMission, id: `mission-${next.id}`, reference: `APIK-${next.id.slice(-6).toUpperCase()}`, title: `Renfort ${blockLabels[next.block].toLowerCase()} · Jacques Prévert`, status: 'OPEN' as const, trigger: 'COMPLIANCE_ENGINE' as const }; queryClient.setQueryData<{ data: Mission[]; total: number }>(queryKeys.missions, (current) => current && current.data.every((item) => item.id !== mission.id) ? { ...current, data: [...current.data, mission], total: current.total + 1 } : current); addToast(`Seuil franchi : ${Math.abs(nextAssigned - next.requiredStaffTotal)} animateur à trouver. La mission est ouverte automatiquement.`, 'error'); }};
  return <EmployerLayout title="Planning de conformité" eyebrow="Semaine du 14 au 20 septembre"><div className="planning-toolbar"><div><strong>École élémentaire Jacques Prévert</strong><span>UAI 0692345K · Villeurbanne · 214 élèves</span></div><Badge tone={hasPedt ? 'info' : 'neutral'}>{hasPedt ? 'PEDT signé' : 'Sans PEDT'}</Badge></div><Card className="planning-card"><div className="planning-grid"><div className="planning-corner">Blocs</div>{dates.map((date) => <div className="planning-day" key={date}>{formatDate(date)}</div>)}{blocks.map((block) => <div className="planning-row" key={block}><div className="planning-block">{blockLabels[block]}</div>{dates.map((date) => { const session = sessions.find((item) => item.date === date && item.block === block); if (!session) return <div className="planning-empty" key={`${date}-${block}`}>—</div>; const isDefect = session.complianceStatus !== 'COMPLIANT'; return <button className={`planning-cell ${isDefect ? 'planning-cell--danger' : 'planning-cell--success'}`} key={session.id} type="button" onClick={() => setSelected(session)}><strong>{session.assignedStaffTotal} / {session.requiredStaffTotal}</strong><span>{session.childrenUnder6 + session.children6AndOver} enfants</span><em>{isDefect ? 'Défaut' : 'Conforme'}</em></button>; })}</div>)}</div></Card>{selected && <aside className="detail-panel" aria-label="Détail du créneau"><button className="panel-close" type="button" onClick={() => setSelected(null)} aria-label="Fermer">×</button><p className="employer-kicker">{formatDate(selected.date)} · {blockLabels[selected.block]}</p><h2>{selected.assignedStaffTotal} présents / {selected.requiredStaffTotal} requis</h2><StatusPill tone={selectedResult?.isCompliant ? 'success' : 'danger'}>{selectedResult?.isCompliant ? 'Conforme' : 'Défaut réglementaire'}</StatusPill><dl className="detail-list"><div><dt>Seuil appliqué</dt><dd>1/{selectedResult?.breakdown.ratio6AndOver} pour les 6 ans et plus</dd></div><div><dt>Configuration</dt><dd>{hasPedt ? 'Avec PEDT' : 'Sans PEDT'} · {selectedResult?.breakdown.durationHours} h</dd></div><div><dt>Écart</dt><dd>{selectedResult?.gap ?? 0}</dd></div><div><dt>Quotas</dt><dd>{quota?.qualified.actual ?? 0} diplômés · {quota?.trainee.actual ?? 0} stagiaires · {quota?.unqualified.actual ?? 0} non qualifiés</dd></div></dl><Button variant="primary" onClick={() => navigate(`/employeur/missions/mission-${selected.id}`)}>Diffuser le besoin</Button>{selected.assignedStaffTotal > 0 && <Button variant="danger" loading={removeAnimator.isPending} onClick={() => void remove()}>Retirer un animateur</Button>}</aside>}</EmployerLayout>;
}

export function EmployerMissionPage() {
  const { id = '' } = useParams(); const matchQuery = useEmployerMatchRun(id === 'mission-thu-evening' ? 'match-run-thu-2026-09-17' : 'match-run-thu-2026-09-17'); const missionsQuery = useEmployerMissions(); const contractsQuery = useEmployerContracts(); const acceptCandidate = useAcceptCandidate(); const queryClient = useQueryClient(); const { addToast } = useToast(); const [accepted, setAccepted] = useState<Candidate | null>(null); const mission = missionsQuery.data?.data.find((item) => item.id === id) ?? demoMission; const run = matchQuery.data; const contract = contractsQuery.data?.data[0];
  const accept = async (candidate: Candidate) => { await acceptCandidate.mutateAsync({ missionId: mission.id, candidateId: candidate.id }); setAccepted(candidate); queryClient.setQueryData<{ data: Mission[]; total: number }>(queryKeys.missions, (current) => current ? { ...current, data: current.data.map((item) => item.id === mission.id ? { ...item, status: 'FILLED' as const, filledPositions: 1 } : item) } : current); queryClient.setQueryData<{ data: CareSession[]; total: number }>(queryKeys.sessions, (current) => current ? { ...current, data: current.data.map((session) => session.id === 'session-thu-evening' ? { ...session, assignedStaffTotal: session.requiredStaffTotal, complianceStatus: 'COMPLIANT' as const } : session) } : current); addToast('Mission pourvue : le créneau repasse conforme et le contrat est prêt.', 'info'); };
  return <EmployerLayout title={mission.title} eyebrow={`Mission ${mission.reference}`}><div className="mission-detail-layout"><div className="mission-detail-main"><Card><div className="mission-status-line"><StatusPill tone={accepted ? 'success' : 'warning'}>{accepted ? 'Pourvue' : 'Ouverte'}</StatusPill><span>{formatDate(mission.startDate)} · {blockLabels[mission.block]} · {mission.totalHours} h</span></div><h2>{mission.description}</h2><p>École élémentaire Jacques Prévert · 69100 Villeurbanne</p><div className="mission-facts"><span><strong>{mission.requiredPositions}</strong> poste</span><span><strong>{mission.hourlyRateCents / 100} €</strong> brut / heure</span><span><strong>BAFA / BPJEPS</strong> recommandé</span></div></Card>{accepted && <AutomationTimeline />}<Card><div className="section-heading"><div><p className="employer-kicker">Moteur de matching · {run?.algorithmVersion}</p><h2>Candidats compatibles</h2></div><Badge tone="info">{run?.eligible.length ?? 0} profils</Badge></div><div className="candidate-list">{run?.eligible.map((candidate) => <CandidateCard candidate={candidate} key={candidate.id} onAccept={() => void accept(candidate)} disabled={Boolean(accepted) || acceptCandidate.isPending} />)}</div></Card><Card><details><summary>Candidats écartés ({run?.rejected.length ?? 0})</summary><div className="rejected-list">{run?.rejected.map((candidate) => <div className="rejected-row" key={candidate.id}><span><strong>{candidate.firstName} {candidate.lastName}</strong><small>{candidate.distanceKm} km · {candidate.qualificationLevel}</small></span><StatusPill tone="danger">{candidate.rejectionLabel ?? 'Verrou bloquant'}</StatusPill></div>)}</div></details></Card></div><aside className="mission-detail-side">{accepted && contract ? <ContractPreview contract={contract} /> : <Card><h2>Pourquoi ce besoin ?</h2><p>Le jeudi soir, 5 animateurs sont présents pour 6 requis. La mission s’ouvre sur franchissement du seuil.</p><Link className="employer-primary-link" to="/employeur/planning">Voir le créneau</Link></Card>}</aside></div></EmployerLayout>;
}

function CandidateCard({ candidate, onAccept, disabled }: { candidate: Candidate; onAccept: () => void; disabled: boolean }) { const breakdown = candidate.scoreBreakdown; return <article className="candidate-card"><div className="candidate-head"><div><h3>{candidate.firstName} {candidate.lastName}</h3><p>{candidate.qualificationLevel === 'QUALIFIED' ? 'Diplômé' : candidate.qualificationLevel === 'TRAINEE' ? 'Stagiaire' : 'Non qualifié'} · {candidate.experienceYears} ans d’expérience · {candidate.distanceKm} km</p></div><strong className="candidate-score">{candidate.score}<small>/100</small></strong></div>{breakdown && <div className="score-block"><div className="score-bar"><span style={{ width: `${breakdown.proximity}%` }} /><span style={{ width: `${breakdown.qualification}%` }} /><span style={{ width: `${breakdown.experience}%` }} /><span style={{ width: `${breakdown.continuity}%` }} /></div><div className="score-legend"><span>Proximité {breakdown.proximity}</span><span>Qualification {breakdown.qualification}</span><span>Expérience {breakdown.experience}</span><span>Continuité {breakdown.continuity}</span></div></div>}<Button variant="secondary" disabled={disabled} onClick={onAccept}>{disabled ? 'Mission pourvue' : 'Sélectionner ce candidat'}</Button></article>; }
function AutomationTimeline() { return <Card><p className="employer-kicker">Automatisation</p><h2>La suite est déjà lancée</h2><ol className="automation-timeline"><li><strong>Contrat généré</strong><span>Prêt à être relu</span></li><li><strong>Notification Discord</strong><span>Direction et animateur prévenus</span></li><li><strong>Relance J+1</strong><span>Programmée automatiquement</span></li></ol></Card>; }
function ContractPreview({ contract }: { contract: NonNullable<ReturnType<typeof useEmployerContracts>['data']>['data'][number] }) { return <Card><p className="employer-kicker">Aperçu du contrat</p><h2>{contract.reference}</h2><dl className="detail-list"><div><dt>Motif du recours</dt><dd>{contract.recourseReason}</dd></div><div><dt>Qualification</dt><dd>{contract.jobQualification}</dd></div><div><dt>Période</dt><dd>{contract.startDate} → {contract.endDate}</dd></div><div><dt>Lieu</dt><dd>{contract.workplaceAddress}</dd></div><div><dt>Rémunération</dt><dd>{(contract.hourlyRateCents / 100).toFixed(2)} € brut / heure</dd></div><div><dt>Période d’essai</dt><dd>{contract.trialPeriodDays} jour</dd></div></dl></Card>; }
